### ISSUE TITLE
Setup Connection uses Europe api_domain by default

### ISSUE THREAD

**Issue by alejorivera** [rikas/zoho_hub#17]
Thanks for open sourcing this — it's saved me so much time already. You are awesome!

Basically, it'd be cool to infer which api_domain to use from the Configuration.

**Comment by rikas** [comment]
Hi @alejorivera,

What do you mean? That should happen. What's the use case where that is not happening?

**Comment by TimCummings** [comment]
EU is the default `api_domain`, but you can pass an explicit domain in the configure block, e.g.:

```ruby
ZohoHub.configure do |config|
  ...
  config.api_domain = 'https://accounts.zoho.com'
  ...
end
```

**Comment by rikas** [comment]
Yep, what @TimCummings said should work. Let me know if it doesn't.

Closing this ticket for now.

**Comment by alejorivera** [comment]
Ok, I should have provided more context. I did setup the api_domain in the initializer:
``` ruby
ZohoHub.configure do |config|
  config.api_domain = 'https://accounts.zoho.com' # Note that this is the US domain.
end
```

However, when doing:
``` ruby
ZohoHub.setup_connection access_token: 'ACCESS_TOKEN'
```
The default API_domain used is the European one, as opposed to the US one, even though I set the US domain as my default in the config.

Does that make sense?

Would be cool to have a method somewhere similar to this:
``` ruby
case config.api_domain
    when "https://accounts.zoho.com"
      "https://www.zohoapis.com"
    when "https://accounts.zoho.eu"
      "https://www.zohoapis.eu"
    when "https://accounts.zoho.com.cn"
      "https://www.zohoapis.com.cn"
    end
```

Sorry if this was more confusing than helpful, and well, thank you anyways!

**Comment by TimCummings** [comment]
Thanks for clarifying, that makes more sense.

Currently, if using a domain other than the default (EU), you also have to pass the domain to `setup_connection` (you may already be aware of this, I just want to mention it for completeness.), e.g.:

```ruby
ZohoHub.setup_connection access_token: 'ACCESS_TOKEN', api_domain: 'https://www.zohoapis.com'
```

It's not a huge burden, but your suggestion would make things a little easier. I'll try to work on a PR tonight or tomorrow.

**Comment by TimCummings** [comment]
It may also be worth mentioning that you can probably rely on the `Auth.refresh_token` response to set this value for you (this was a stumbling point for me initially; I was trying to set it myself.) You can see an example of this in `bin/console':
```ruby
token_params = ZohoHub::Auth.refresh_token(ENV['ZOHO_REFRESH_TOKEN'])
ZohoHub.setup_connection(token_params)
```

**Comment by rikas** [comment]
@alejorivera thanks for clarifying!

@TimCummings if you could do the PR it would be awesome! :pray:
