### ISSUE TITLE
Redirect URL or Refresh Token

### ISSUE THREAD

**Issue by mikejmorgan** [rikas/zoho_hub#24]
Hi there!  Thanks for the better documentation for this gem!  It really helps a novice like me!  Looking through the doc, the refresh token is still a TODO.  I am using offline access, but I am not successful at utilizing the refresh token without a user manually re-connecting to their Zoho account.  I either need a better understanding of the refresh token, or is there a way that I can send some parameters to the refresh url?  My goal would be to tag some REFRESH_URL?return_url=some/path that way I could make it easier for my end users?

**Comment by TimCummings** [comment]
I'm not sure how quickly I can update the README; my day job has been crazy and we are on the brink of our busy season. But I'm happy to try and help!

To my knowledge, the only point at which a user can be prompted for credentials is during the authorization request (there may be others of which I'm unaware; my use case has been narrow so far.) If your users are being prompted for Zoho credentials, I'd start examining the [auth request](https://www.zoho.com/crm/developer/docs/api/auth-request.html). Of note, please verify that the [API credentials' type is](https://www.zoho.com/crm/developer/docs/api/auth-request.html#self-client) `Self client`.

Have you been able to generate a refresh token and you're having trouble using it to re-generate access tokens once they expire, or are you unable to get a refresh token?

**Comment by Fabien-Wecasa** [comment]
My 2 cents...
As @TimCummings says, there is no need to re-connect to your Zoho account once you have a refresh token. These token do not expire (however, they can be invalidated, e.g. if more than 20 refresh token are created).

I also had some problem generating the refresh token (only the access token was returned by `ZohoHub::Auth.get_token`). Here is what I do now:
* Get a (short-lived) grant token by following the URL given by `ZohoHub::Auth.auth_url(access_type: 'offline')`
* Get the refresh token with `ZohoHub::Auth.get_token(<grant token>)`
-> {:access_token=> "..." **:refresh_token=>"..."**, :expires_in_sec=>3600, :api_domain=>"...", :token_type=>"Bearer", :expires_in=>3600000}

Use this refresh token in the connection setup:
```
ZohoHub.setup_connection(
  # The access_token has a lifetime of 1h.
  # We define a dummy token so that the first call returns INVALID_TOKEN / "invalid oauth token".
  # This error triggers a token refresh with the refresh_token below (no expiration for this one).
  # This dummy token can't be empty.
  access_token: "xxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  refresh_token: ENV['ZOHO_REFRESH_TOKEN']
)
```

Maybe it helps... Good luck !

**Comment by mikejmorgan** [comment]
@Fabien-Wecasa @TimCummings Thank you so much for your insight!  I really appreciate both of your help.  I will try to implement these things today!

**Comment by mikejmorgan** [comment]
@Fabien-Wecasa, to get a bit of clarity, I'd like to share my code on the redirect_uri
`def connect_account

		grant_token = params["code"]
		response = ZohoHub::Auth.get_token(grant_token)

		ZohoHub.setup_connection(
		  # The access_token has a lifetime of 1h.
		  # We define a dummy token so that the first call returns INVALID_TOKEN / "invalid oauth token".
		  # This error triggers a token refresh with the refresh_token below (no expiration for this one).
		  # This dummy token can't be empty.
		  access_token: "xxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
		  refresh_token: ENV['ZOHO_REFRESH_TOKEN']
		)

		current_user.update_attributes(
			zoho_token: response[:access_token],
			zoho_token_retrieved_at: Time.now,
			zoho_location: params["location"],
			zoho_accounts_server: params["accounts-server"],
			zoho_refresh_token: response[:refresh_token],
			zoho_expires_in_sec: response[:expires_in_sec],
			zoho_api_domain: response[:api_domain],
			zoho_token_type: response[:token_type]
		)
		flash[:notice] = "You are now connected to Zoho."
		redirect_to controller: 'home', action: 'index'
	end`
Am I putting the ZohoHub.setup_connection in the right spot?  Should I also make it equal to `response`  to save the my Users table?

**Comment by Fabien-Wecasa** [comment]
Hello @mikejmorgan ,
I don't think you use the different tokens as you should. 1 refresh token should be enough for all your users. So the `ZohoHub::Auth.get_token(grant_token)` must be done only once in your console, and you must keep the given refresh token for all future needs -> the `refresh_token` of the `setup_connection` is a constant.
I think in most cases, this function `setup_connection` can be called only once at initialization, after the `configure` ([point 2 of the README](https://github.com/rikas/zoho_hub#2-configure-zohohub-with-your-credentials)). Maybe you can try this ?

**Comment by mikejmorgan** [comment]
Okay.  Thank you everyone for your help.  I've work with a friend of mine to work through what you guys said and have gotten it working!  Thanks again!

**Comment by pkayokay** [comment]
> My 2 cents...
> As @TimCummings says, there is no need to re-connect to your Zoho account once you have a refresh token. These token do not expire (however, they can be invalidated, e.g. if more than 20 refresh token are created).
> 
> I also had some problem generating the refresh token (only the access token was returned by `ZohoHub::Auth.get_token`). Here is what I do now:
> 
> * Get a (short-lived) grant token by following the URL given by `ZohoHub::Auth.auth_url(access_type: 'offline')`
> * Get the refresh token with `ZohoHub::Auth.get_token(<grant token>)`
>   -> {:access_token=> "..." **:refresh_token=>"..."**, :expires_in_sec=>3600, :api_domain=>"...", :token_type=>"Bearer", :expires_in=>3600000}
> 
> Use this refresh token in the connection setup:
> 
> ```
> ZohoHub.setup_connection(
>   # The access_token has a lifetime of 1h.
>   # We define a dummy token so that the first call returns INVALID_TOKEN / "invalid oauth token".
>   # This error triggers a token refresh with the refresh_token below (no expiration for this one).
>   # This dummy token can't be empty.
>   access_token: "xxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
>   refresh_token: ENV['ZOHO_REFRESH_TOKEN']
> )
> ```
> 
> Maybe it helps... Good luck !

@Fabien-Wecasa once you already know your refresh token, you can just use this method. So that you don't have to pass your dummy `access_token`.

```
token_params = ZohoHub::Auth.refresh_token(ENV['ZOHO_REFRESH_TOKEN'])
# ZohoHub.setup_connection(token_params)
```

**Comment by Fabien-Wecasa** [comment]
@pkayokay You are right, thanks ! :+1:
