### ISSUE TITLE
Custom request path?

### ISSUE THREAD

**Issue by artsyca** [rikas/zoho_hub#39]
The convention of Rails is to use `PascalCase` class names, whereas Zoho of course prefers the uniquely eccentric `Pascal_Snake_Case` or `Title_Case_Underscored` so a module named `MyModule` in rails would need to be called `My_Module` in Zoho --

At present the ZohoHub::BaseRecord will not insert underscores and I've monkey patched my class thusly:

```
class MyModule < ZohoHub::BaseRecord
  ..
  class << self
    def request_path
      # TODO: is there any other way to override this?
      ZohoHub::BaseRecord.request_path('My_Modules')
    end
  end
  ..
end
```

Is this the correct way to proceed?

**Comment by Fabien-Wecasa** [comment]
To override the `zoho_hub` default behavior, you can simply define `request_path`:
```
class MyModule < ZohoHub::BaseRecord
  request_path 'My_Modules'
  ...

```
