### ISSUE TITLE
How to delete a deal?

### ISSUE THREAD

**Issue by ueki-hikonuki** [rikas/zoho_hub#56]
I can create a deal with the following class.

class Deal < ZohoHub::BaseRecord
  attributes :id, :deal_name, :account_name, :amount, :closing_date, :stage, :contact_name, :description, :notes
end

However, I am not sure how to delete a deal.

Deal.delete(deal_id) does not seem to be working.

Thank you.

**Comment by Fabien-Wecasa** [comment]
The deletion is not handled yet. There is an open PR #52 for that.
If/when it is merged, you'll be able to call `Deal.delete_record(deal_id)` or `deal.delete_record`.

**Comment by ueki-hikonuki** [comment]
I see. Thank you.
