### ISSUE TITLE
Is it possible to use different names for base records?

### ISSUE THREAD

**Issue by pmalliak** [rikas/zoho_hub#67]
Hello I already have leads and accounts models in my app. Is it possible to use names like ZohoLead or ZohoAccount instead?

**Comment by rikas** [comment]
@pmalliak the classes here are namespaced, you can use `ZohoHub::Lead` and `ZohoHub::Account`. Maybe the problem is that you're including the ZohoHub namespace in your app and then it clashes with your models?

I'm closing as I think that having the namespaced classes should be enough.
